- name: Deploy Inventory Microservice
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop existing container
      ansible.builtin.command: docker stop inventory-service
      ignore_errors: yes
    - name: Remove existing container
      ansible.builtin.command: docker rm inventory-service
      ignore_errors: yes
    - name: Run new container
      ansible.builtin.command: docker run -d --name inventory-service -p 8082:8080 inventory-service:latest
